cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

lapland_in_sweden/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('tourprograms/', include('tourprograms.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourprograms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_tourprograms, name='tourprograms'),
    path('<tourprogram_id>', views.tourprogram_detail,
         name='tourprogram_detail'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum

from django_countries.fields import CountryField

from tourprograms.models import Tourprogram
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.grand_total = self.order_total
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    tourprogram = models.ForeignKey(Tourprogram, null=False, blank=False,
                                    on_delete=models.CASCADE)
    select_departure_date = models.CharField(max_length=254, null=True,
                                             blank=True)
    number_people_adult = models.IntegerField(null=False, blank=False,
                                              default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.tourprogram.priceadult \
            * self.number_people_adult
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.tourprogram.sku} on order {self.order.order_number}'

tourprograms/models.py
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Tourprogram(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    region = models.CharField(max_length=254)
    maximum = models.IntegerField()
    date = models.CharField(max_length=254, null=True, blank=True)
    priceadult = models.IntegerField()
    pricechild = models.IntegerField()
    departure_date = models.CharField(max_length=254)
    estimated_times = models.CharField(max_length=254, null=True, blank=True)
    description = models.TextField()
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True,
                                 blank=True)
    included = models.CharField(max_length=254, null=True, blank=True)
    not_included = models.CharField(max_length=254, null=True, blank=True)
    meeting_place = models.CharField(max_length=254)
    note = models.TextField(null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

tourprograms/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Tourprogram, Category

# Create your views here.


def all_tourprograms(request):
    """
    A view to show all tour programs, including sorting and search queries
    """

    tourprograms = Tourprogram.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                tourprograms = tourprograms.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            tourprograms = tourprograms.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            tourprograms = tourprograms.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               "You didn't enter any search criteria!")
                return redirect(reverse('tourprograms'))

            queries = Q(name__icontains=query) | \
                Q(description__icontains=query)
            tourprograms = tourprograms.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'tourprograms': tourprograms,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'tourprograms/tourprograms.html', context)


def tourprogram_detail(request, tourprogram_id):
    """ A view to show individual tourprogram details """

    tourprogram = get_object_or_404(Tourprogram, pk=tourprogram_id)

    context = {
        'tourprogram': tourprogram,
    }

    return render(request, 'tourprograms/tourprogram_detail.html', context)

tourprograms/templates/tourprograms/tourprogram_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <h3 class="mb-0 page-top">{{ tourprogram.name }}</h3>
        <div class="row">
            <div class="col-12 col-md-12 col-lg-6 offset-lg-1">
                <div class="image-container my-5">
                    {% if tourprogram.image %}
                        <a href="{{ tourprogram.image_url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ tourprogram.image_url }}" alt="{{ tourprogram.name }}">
                        </a>
                        {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ tourprogram.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4">
                <div class="tourprogram-details-container mb-5 mt-md-5">
                    <h5 class="lead text-left font-weight-bold">Price </h5>
                    <p class="lead mb-0 text-left">Adult: {{ tourprogram.priceadult }} SEK</p>
                    <p class="lead mb-0 text-left child-event-old">Child: {{ tourprogram.pricechild }} SEK</p><p class="lead text-left font-weight-bold child-event"> <i class="far fa-hand-point-right"></i> free! (open event)</p>
                    {% if tourprogram.category %}
                        <p class="small mt-1 mb-0">
                            <a class="text-muted" href="{% url 'tourprograms' %}?category={{ tourprogram.category.name }}">
                                <i class="fas fa-tag mr-1"></i>{{ tourprogram.category.friendly_name }}
                            </a>
                        </p>
                    {% endif %}                        
                    {% if tourprogram.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ tourprogram.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    <form class="form" action="{% url 'add_to_cart' tourprogram.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-12">
                                <p class="detail_item"><strong>Departure date:</strong></p>
                                <div class="form-group w-75">
                                    <div class="input-group">
                                        <div class="input-group-text">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                    <input class="form-control" id="id_select_departure_date" name="select_departure_date" type="text"  placeholder="MM/DD/YYYY" required>            
                                    </div>
                                </div>
                            </div>        
                            <div class="col-12">
                                <p class="detail_item"><strong>Number of Adult:</strong></p>
                                <div class="form-group w-75">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-ppl btn btn-black rounded-0" 
                                                data-item_id="{{ tourprogram.id }}" id="decrement-ppl_{{ tourprogram.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control ppl_input" type="number"
                                            name="number_people_adult" value="1" min="1" max="{{ tourprogram.maximum }}"
                                            data-item_id="{{ tourprogram.id }}"
                                            id="id_ppl_{{ tourprogram.id }}" required>
                                        <div class="input-group-append">
                                            <button class="increment-ppl btn btn-black rounded-0"
                                                data-item_id="{{ tourprogram.id }}" id="increment-ppl_{{ tourprogram.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% if tourprogram.maximum < 999 %}
                            <div class="col-12 note-group">
                                <p>More than {{ tourprogram.maximum }} people, please contact us. (Special offer for a group!)</p>
                                <a href="{% url 'contact' %}">Ask us!</a>
                            </div>
                            {% endif %}
                            <div class="col-12">
                                <a href="{% url 'tourprograms' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Back to list</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Cart">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        </div>
                    </form>                    
                </div>
            </div>
            <div class="col-12 col-md-12 col-lg-10 offset-lg-1">
                <div class="row">
                <div class="col-sm-6 col-md-3 text-center small-info" id="program_region">Region <p><strong>{{ tourprogram.region }}</strong></p></div>
                <div class="col-sm-6 col-md-3 text-center small-info" id="program_maximum">Maximum<p><strong>
                    {% if tourprogram.maximum == 999 %}
                        No limit
                    {% else %}
                        {{ tourprogram.maximum }}
                    {% endif %}</strong></p>
                </div>
                <div class="col-sm-6 col-md-3 text-center small-info" id="departure_date">Departure Date<p><strong>{{ tourprogram.departure_date }}</strong></p></div>
                <div class="col-sm-6 col-md-3 text-center small-info" id="est_time">Estimated Time<p><strong>{{ tourprogram.estimated_times }}</strong></p></div>
                </div>
                <div class="detail_item">Description
                    <p> - {{ tourprogram.description }}</p>
                </div>
                <div class="detail_item">Included
                    <p> - {{ tourprogram.included }}</p>
                </div>
                <div class="detail_item">Not included
                    <p> - {{ tourprogram.not_included }}</p>
                </div>
                <div class="detail_item">Meeting Place
                    <p> - {{ tourprogram.meeting_place }}</p>
                </div>
                <div class="detail_item">Note
                    <p> - {{ tourprogram.note }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    <script type="text/javascript">
        /* 
        Sample function that returns boolean in case the browser is Internet Explorer
        Source: https://jsfiddle.net/alvaroAV/svvz7tkn/ 
        */
        function isIE() {
            ua = navigator.userAgent;
            /* MSIE used to detect old browsers and Trident used to newer ones*/
            var is_ie = ua.indexOf("MSIE ") > -1 || ua.indexOf("Trident/") > -1;

            return is_ie;
        }
        /* Create an alert to show if the browser is IE or not */
        if (isIE()) {
            alert('We don\'t support the calendar function in Internet Explorer. Please use other browsers.');
        }
    </script>
{{ block.super }}
{% include 'tourprograms/includes/people_input_script.html' %}
{% endblock %}

tourprograms/templates/tourprograms/tourprograms.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-3">
                <h2 class="logo-font page-top">Tour Programs</h2>
                {% for c in current_categories %}
                    <a class="category-badge text-decoration-none" href="{% url 'tourprograms' %}?category={{ c.name }}">
                        <span class="p-2 mt-2 badge badge-white text-black rounded-0 border border-dark">{{ c.friendly_name }}</span>
                    </a>
                {% endfor %}
                <hr class="w-50 mb-1">
            </div>
        </div>
        <div class="row">
            <div class="tourprogram-container col-10 offset-1">
                <div class="row mt-1 mb-2">
                    <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                        <div class="sort-select-wrapper w-50">
                            <select id="sort-selector" class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                                <option value="priceadult_asc" {% if current_sorting == 'priceadult_asc' %}selected{% endif %}>Price (low to high)</option>
                                <option value="priceadult_desc" {% if current_sorting == 'priceadult_desc' %}selected{% endif %}>Price (high to low)</option>
                                <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                                <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                                <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                                <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                                <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)</option>
                                <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 order-md-first">
                        <p>Click an image. You can see the detailed tour information.</p>
                        <p class="text-muted mt-3 text-center text-md-left">
                            {% if search_term or current_categories or current_sorting != 'None_None' %}
                                <span class="small"><a href="{% url 'tourprograms' %}">Tour Programs Home</a> | </span>
                            {% endif %}
                            {{ tourprograms|length }} Tour programs{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                        </p>
                    </div>
                </div>
                <div class="row">
                    {% for tourprogram in tourprograms %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                {% if tourprogram.image %}
                                <a href="{% url 'tourprogram_detail' tourprogram.id %}">
                                    <img class="card-img-top img-fluid" src="{{ tourprogram.image_url }}" alt="{{ tourprogram.name }}">
                                </a>
                                {% else %}
                                <a href="{% url 'tourprogram_detail' tourprogram.id %}">
                                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ tourprogram.name }}">
                                </a>
                                {% endif %}
                                <div class="card-body pb-0">
                                    <p class="mb-0"><strong>{{ tourprogram.name }}</strong></p>
                                </div>
                                <div class="card-footer bg-white pt-0 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <p class="lead mb-0 text-left adult-price">Adult: {{ tourprogram.priceadult }} SEK</p>
                                            <p class="lead mb-0 text-left child-event-old">Child: {{ tourprogram.pricechild }} SEK</p><p class="lead mb-0 text-left font-weight-bold child-event"> <i class="far fa-hand-point-right"></i> free!</p>
                                            {% if tourprogram.category %}
                                            <p class="small mt-1 mb-0">
                                                <a class="text-muted" href="{% url 'tourprograms' %}?category={{ tourprogram.category.name }}">
                                                    <i class="fas fa-tag mr-1"></i>{{ tourprogram.category.friendly_name }}
                                                </a>
                                            </p>
                                            {% endif %}
                                            {% if tourprogram.rating %}
                                                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ tourprogram.rating }} / 5</small>
                                            {% else %}
                                                <small class="text-muted">No Rating</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                                <hr>
                            </div>
                        {% endif %}                        
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="col-12 d-none d-xl-block mb-5">
                                <hr>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="btt-button shadow-sm rounded-0 border border-black">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
        </a>	
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('.btt-link').click(function(e) {
		    window.scrollTo(0,0)
	    })
    </script>

    <script type="text/javascript">
        $('#sort-selector').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);
            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } 
            else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}